const USER = {
    REGISTER: 'USER_REGISTER',
    UNREGISTER: 'USER_UNREGISTER',
    GET_SUMMARY: 'USER_GET_SUMMARY'
}

const GAME = {
    GET: 'GAME_GET_MY_GAME',
    CREATE: 'GAME_CREATE',
    JOIN: 'GAME_JOIN',
    MOVE: 'GAME_MOVE',
    FORFIT: 'GAME_FORFIT',
    COMPLETE: 'GAME_COMPLETE',
    REFRESH: 'GAME_REFRESH'
};

const LEADERBOARDS = {
    LIST: 'LEADERBOARDS_LIST'
};

const GAMES = {
    LIST: 'GAMES_LIST'
}

export default {
    USER,
    GAME,
    GAMES,
    LEADERBOARDS
}